#!/usr/bin/env python3
"""Export completed controlled-study fixtures and measured invocation provenance."""
import datetime
import hashlib
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    run = ROOT / "results/review_controls_v1"
    result_path = ROOT / "results/review_controls_v1.json"
    if not result_path.exists():
        raise SystemExit("Study is incomplete; no completed release can be exported")
    manifest = json.loads((run / "manifest.json").read_text())
    responses = [json.loads(f.read_text()) for f in (run / "responses").glob("*.json")]
    if len(responses) != len(manifest["jobs"]):
        raise ValueError("Missing response records")
    dataset = ROOT / "benchmark/review_v1"
    dataset.mkdir(parents=True, exist_ok=True)
    public, labels, seen = [], [], set()
    for job in manifest["jobs"]:
        request = {k: v for k, v in job.items() if k not in {"model", "replicate", "order", "request_id"}}
        digest = hashlib.sha256(json.dumps(request, sort_keys=True).encode()).hexdigest()
        if digest in seen:
            continue
        seen.add(digest)
        opaque_id = f"controlled-{len(public):04d}"
        public.append({"id": opaque_id, "prompt": request["prompt"], "response_schema": request.get("response_schema")})
        labels.append({"id": opaque_id, **{k: v for k, v in request.items() if k not in {"prompt", "response_schema"}}})
    checksums = {}
    for name, rows in [("prompts.jsonl", public), ("labels.jsonl", labels)]:
        text = "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows)
        (dataset / name).write_text(text)
        checksums[name] = hashlib.sha256(text.encode()).hexdigest()
    (dataset / "SHA256.json").write_text(json.dumps(checksums, indent=2) + "\n")
    (dataset / "README.md").write_text(
        "# Controlled revision study fixtures\n\n"
        "prompts.jsonl contains the initial prompt and output schema supplied to the model, with opaque release IDs. "
        "labels.jsonl contains construction metadata and semantic targets; some metadata also constructs later user turns. "
        "Use run_review_controls.py and its recorded follow-up builder to reproduce conversations. "
        "Never append the whole label file or condition names to model input. "
        "The full randomized execution manifest, separate replicates, failures and provider envelopes are retained in results/review_controls_v1/.\n\n"
        "These are synthetic tasks, generated by the source modules used by run_review_controls.py. All cases are evaluation cases; "
        "there is no claim of an independently authored or provider-unseen test distribution. "
        "The fixtures accompany the repository under its existing license.\n")
    requested_models = defaultdict(Counter)
    costs, attempts, model_turns = [], 0, 0
    for response in responses:
        records = response.get("attempts", response.get("transcript", []))
        attempts += len(records)
        model_turns += response.get("completed_turns", 1)
        for record in records:
            envelope = record.get("envelope", {})
            if "total_cost_usd" in envelope:
                costs.append(envelope["total_cost_usd"])
            requested_models[response["model"]].update(envelope.get("modelUsage", {}).keys())
    provenance = {
        "exported_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "dataset_prompts": len(public), "response_records": len(responses), "model_turn_records": model_turns,
        "attempt_or_turn_records": attempts, "transport_failures": sum(not r["transport_ok"] for r in responses),
        "unparsed_envelopes": sum(r["parsed"] is None for r in responses),
        "cli_version": manifest["cli_version"], "flags": manifest["flags"],
        "model_usage_keys_by_requested_alias": {k: dict(v) for k, v in requested_models.items()},
        "reported_cost_sum_usd": sum(costs),
        "cost_scope": "sum of CLI-reported envelopes; failed requests may lack billing metadata and resumed sessions may report cumulative fields; not an invoice",
        "manifest_sha256": hashlib.sha256((run / "manifest.json").read_bytes()).hexdigest(),
        "results_sha256": hashlib.sha256(result_path.read_bytes()).hexdigest(), "dataset_sha256": checksums,
        "interface_scope": "safe mode, explicit system prompt, no external tools; provider-managed policy and serving state are not observable",
    }
    (ROOT / "results/review_invocation_audit.json").write_text(json.dumps(provenance, indent=2) + "\n")
    print(json.dumps({"dataset_prompts": len(public), "responses": len(responses), "transport_failures": provenance["transport_failures"]}))


if __name__ == "__main__":
    main()
